spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ### mvc: pathmatch etc.. to SOLVE THE PROBLEM OF  Failed to start bean 'documentationPluginsBootstrapper
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: org.commerce.gestiondestock.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081
  netty:
    h2c-max-content-length:

flickr:
  apikey: 02fc2347bd7d33b972942cca2038c249
  apiSecret: 36e741b229e441d3
  appkey: 72157720842069255-fba3485f3cf1bb32
  appSecret: 9117fcd33a85b17b
